DROP TABLE IF EXISTS user CASCADE;

CREATE TABLE user (
	id BIGINT AUTO_INCREMENT,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	age INT NOT NULL,
	username VARCHAR(255) UNIQUE NOT NULL,
	email_address VARCHAR(255) UNIQUE NOT NULL,
	PRIMARY KEY (id)
);